<h2>Post some description</h2>
<?php echo "<p>" . $this->response->getContent() . "</p>"; ?>
<?php echo $this->tag->form("post"); ?>

<p>
    <label for="description">Description</label>
    <?php echo $this->tag->textField("description"); ?>
</p>
<p>
    <?php echo $this->tag->submitButton("Upload"); ?>
</p>

</form>
<?php echo $this->tag->linkTo(['index', 'back', "class" => "btn btn-warning"]);
