<?php
echo "<h1>Welcome back</h1>";
$this->tag->setTitle("hello user ' " . $name . " '");
echo $this->tag->getTitle();
echo "<br>";

echo "<hr>";
echo "<h2>Date & time on server</h2>";
echo $this->date;
echo "<hr>";
echo $this->tag->linkTo(
    [
    'login/logout',
    'Log out!',
    "class" => "btn btn-danger mx-5"
    ]
);
echo $this->tag->linkTo(
    [
    'post/index',
    'Post something',
    "class" => "btn btn-warning"
    ]
);